### ISSUE TITLE
[DOC] URL Reference for Next steps' what_else does not resolve here in Github but is in the Doc page.

### ISSUE THREAD

**Issue by AnneTheAgile** [PythonCharmers/python-future#134]
//updated Title per new understanding in next remark.

hi, on the page;  python-future/docs/quickstart.rst , aka 
https://github.com/PythonCharmers/python-future/blob/fd44b5ec04d1e08ed9ef38a69d042b158acb0595/docs/quickstart.rst#id24

It says ; 
````
Next steps
For more information about writing Py2/3-compatible code, see:
    :ref:`compatible-idioms`
    :ref:`what-else`.
````
but neither of those references go to other locations? 

thank you! I look forward to writing some back-compatible code :). AnneTheAgile

**Comment by AnneTheAgile** [comment]
The links do resolve correctly on the actual docs! I was looking here in github because I was concerned about out of date docs. [3]  I don't know how the doc pages are generated. 

If you would be so kind, I'm  wondering where the body of [2] lives here in github? I will change the title as well.

The page that lists them correctly is ; http://python-future.org/quickstart.html
[1].So this,
http://python-future.org/compatible_idioms.html#compatible-idioms
is aka  python-future/docs/compatible_idioms.rst
https://github.com/PythonCharmers/python-future/blob/fd44b5ec04d1e08ed9ef38a69d042b158acb0595/docs/compatible_idioms.rst

[2].But   this, I'm  still a bit confused;
http://python-future.org/what_else.html#what-else
I thought would go to  python-future/docs/what_else.rst
but that page is relatively empty?
https://github.com/PythonCharmers/python-future/blob/fd44b5ec04d1e08ed9ef38a69d042b158acb0595/docs/what_else.rst

2A.Maybe what_else is sort of deleted but not yet removed from references? 
https://github.com/PythonCharmers/python-future/search?utf8=%E2%9C%93&q=what-else&type=Code

[3] I was misreading this doc page. http://python-future.org/overview.html , somehow I  saw the 2013 and didn't see the 2013-2015.

**Comment by edschofield** [comment]
Hi @AnneTheAgile, Thanks for your comments. The docs are generated using Sphinx (http://sphinx-doc.org) by typing ``make html`` in the ``docs/`` folder. This requires the packages ``sphinx`` and ``sphinx_bootstrap_theme``.

In answer to your question about the What Else page being empty, I think you were misled by GitHub's incomplete rendering of the ReStructured Text. Clicking the "raw" button shows the actual content of the file:

https://raw.githubusercontent.com/PythonCharmers/python-future/fd44b5ec04d1e08ed9ef38a69d042b158acb0595/docs/what_else.rst

It includes content from several other ``.rst`` files.

**Comment by edschofield** [comment]
I believe this works fine. If you have any further problems, please feel free to reopen this issue.
