### ISSUE TITLE
Constants missing from http.client on Python 2

### ISSUE THREAD

**Issue by samh** [PythonCharmers/python-future#137]
The [http.client](https://docs.python.org/3/library/http.client.html) module includes a number of constants (`HTTP_PORT`, `HTTPS_PORT`, and integer status codes like `BAD_REQUEST`). On Python 2 using `future`, these are not available from `http.client`.

This appears to be because [httplib](https://docs.python.org/2/library/httplib.html) doesn't include them in `__all__`. It looks like they need to be explicitly imported in future's `http.client` module.

**Comment by edschofield** [comment]
Thanks for asking, Sam! I've added these to the v0.14.x branch.
