### ISSUE TITLE
python-future.org is inaccessible via HTTPS

### ISSUE THREAD

**Issue by QuLogic** [PythonCharmers/python-future#143]
Attempting to navigate to https://python-future.org/ does not work because it is serving the certificate for pythoncharmers.com, which is weird since pythoncharmers.com does not respond at all over HTTPS.

**Comment by yan12125** [comment]
Yes, and PyPI's homepage points to it:
https://github.com/PythonCharmers/python-future/blob/master/setup.py#L99

**Comment by jmadler** [comment]
Dupe of #358
