### ISSUE TITLE
[DOC] Note that struct.pack supports unicode format strings in 2.7.7+

### ISSUE THREAD

**Issue by johnthagen** [PythonCharmers/python-future#147]
On the [Std Lib Incompatibilities Page](http://python-future.org/stdlib_incompatibilities.html#struct-pack) there is a note about how [struct.pack](https://docs.python.org/2/library/struct.html#struct.pack) cannot accept unicode format strings.

This was actually [fixed in Python 2.7.7](https://hg.python.org/cpython/raw-file/f89216059edf/Misc/NEWS) and worth mentioning for developers who do not need to support older versions of Python 2.7.

**Comment by edschofield** [comment]
Thanks, John! I've updated the docs in the v0.14.x branch.
