### ISSUE TITLE
Provide Python 2.6+ compatible count

### ISSUE THREAD

**Issue by xZise** [PythonCharmers/python-future#152]
Could you make the `_count` function in `future.types.newrange` publicly available?

**Comment by xZise** [comment]
By the way I had already written an implementation for pywikibot when it was suggested that the future package should support it. So if you want to have tests you could use them from https://gerrit.wikimedia.org/r/#/c/219396/1/tests/tools_tests.py,cm

**Comment by edschofield** [comment]
Thanks for asking, Fabian. 

This issue only relates to Py2.6. Python 2.7 and above already have an `itertools.count()` function with the `step` parameter.

I've now made the function available as `future.backports.misc.count` in the v0.14.x branch. This gets patched into `itertools` on Py2.6 by calling `future.standard_library.install_aliases()`.

**Comment by edschofield** [comment]
Fixed in v0.15.0.

**Comment by xZise** [comment]
Ah the title may have been misleading. I wanted a “Python 2.7+ compatible count” IN Python 2.6 ;)
