### ISSUE TITLE
`newsuper` fails on Python 2 when used in __init__ method of PyQt sub-classes

### ISSUE THREAD

**Issue by SpotlightKid** [PythonCharmers/python-future#160]
This example fails:

```
# minimal.py
from builtins import super
from PyQt5.QtWidgets import QApplication, QMainWindow


class HelloWorldWin(QMainWindow):
    def __init__(self,*args, **kw):
        super().__init__(*args, **kw)
        self.show()

app = QApplication([])
win = HelloWorldWin()
app.exec_()
 ```

with

```
$ python2 minimal.py 
Traceback (most recent call last):
  File "minimal.py", line 12, in <module>
    win = HelloWorldWin()
  File "minimal.py", line 8, in __init__
    super().__init__(*args, **kw)
  File "/home/chris/work/pyqt5-course/newsuper.py", line 64, in newsuper
    mro = type_or_obj.__mro__
RuntimeError: super-class __init__() of type HelloWorldWin was never called
```

When I change line 65 of `future/builtins/newsuper.py` from

        except AttributeError:

to

        except (AttributeError, RuntimeError):
 
causing the MRO to be retrieved from the class instead of the instance, it works as it should.

My suspicion is that accessing the MRO of an instance of a PyQt class instance somehow triggers a an instance method call, causing the above error because the instance hasn't been initialized yet, but I haven't confirmed this.

**Comment by edschofield** [comment]
Thanks a lot for your feedback, Christopher! I've incorporated your suggested fix into v0.15.2.
