### ISSUE TITLE
test_expandtabs error on Python-2.6

### ISSUE THREAD

**Issue by sagitter** [PythonCharmers/python-future#161]
Hi all,

this error comes out by performing ```future``` tests with Python-2.6:

```
======================================================================
ERROR: test_expandtabs (test_future.test_buffer.BytearrayPEP3137Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-future-0.15.0/tests/test_future/test_buffer.py", line 181, in test_expandtabs
    if sys.maxsize < (1 << 32) and struct.calcsize('P') == 4:
TypeError: Struct() argument 1 must be string, not unicode
----------------------------------------------------------------------
Ran 992 tests in 22.542s
FAILED (errors=1)
```

I'm looking for packaging ```future``` on Fedora and EPEL6/7 ( Red Hat Enterprise Linux (RHEL), CentOS and Scientific Linux (SL), Oracle Linux (OL)) repositories.

This is full log: https://copr-be.cloud.fedoraproject.org/results/sagitter/preprocess/epel-6-i386/future-0.15.0-1.fc22/build.log.gz

Thanks.

**Comment by QuLogic** [comment]
Strange, I have a [build of future](https://copr.fedoraproject.org/coprs/qulogic/obspy/build/105647/) on EPEL 6 that seems to have run just fine.

**Comment by sagitter** [comment]
Indeed, i have used your patch, tested ```future``` by using ```pytest``` and rebuilt successfully.

Thank you.
