### ISSUE TITLE
Incorrect call to pdb in backports.http.client

### ISSUE THREAD

**Issue by migurski** [PythonCharmers/python-future#164]
In `readinto()`, there’s a [call to `pdb` near line 560](https://github.com/PythonCharmers/python-future/blob/v0.15.0/src/future/backports/http/client.py#L560):

    if data[:2] == b"b'":
        # Something has gone wrong
        import pdb
        pdb.set_trace()

This looks to be debugging code left in the library. It’s an unrecoverable interruption, and I have a [sample data file, `au-queensland.zip`](http://data.openaddresses.io/runs/11158/au-queensland.zip), which reliably trips this bug:

    >>> from future import standard_library
    >>> standard_library.install_aliases()
    >>> from urllib.request import urlretrieve
    >>> urlretrieve('http://data.openaddresses.io/runs/11158/au-queensland.zip', '/tmp/au-queensland.zip')

**Comment by edschofield** [comment]
@migurski: Thanks very much for the heads-up! I've fixed this in v0.15.1.
