### ISSUE TITLE
future.builtins.object is injecting "next()" method on Python 2

### ISSUE THREAD

**Issue by megies** [PythonCharmers/python-future#177]
We're doing a `from future.builtins import *` on top of every file, and therefore all of our classes inheriting from `object` end up actually inheriting from `future.types.newobject.newobject`.

I just noticed that this injects a `.next()` into any of our classes that inherit from `object` on Python2:

``` python
o = object()
print("__next__" in dir(o))
print("next" in dir(o))

class O(object):
    pass

o = O()
print("__next__" in dir(o))
print("next" in dir(o))

from future.builtins import object

class O(object):
    pass

o = O()
print("__next__" in dir(o))
print("next" in dir(o))
```

On Python2:

```
False
False
False
False
False
True
```

On Python3:

```
False
False
False
False
False
False
```

`object` doesn't have such a method in neither Python2 or 3.
Can you comment on this?

**Comment by edschofield** [comment]
Thanks for asking, Tobias. Yes, this is deliberate; this is described in the "Custom iterators" section of the Cheat Sheet: http://python-future.org/compatible_idioms.html#custom-iterators

This behaviour allows the following code to work on Py2 as on Py3:

```
from builtins import object
class Upper(object):
    def __init__(self, iterable):
        self._iter = iter(iterable)
    def __next__(self):      # Py3-style iterator interface
        return next(self._iter).upper()  # builtin next() function calls
    def __iter__(self):
        return self

itr = Upper('hello')
assert next(itr) == 'H'
assert list(itr) == list('ELLO')
```

**Comment by jmadler** [comment]
Closing for age.  Please re-open if this is important/valid.
