### ISSUE TITLE
 ImportError: No module named 'future`

### ISSUE THREAD

**Issue by ImmanuelSamuel** [PythonCharmers/python-future#188]
```from future import standard_library```
I am using anaconda3. future seems to be installed (checked with pip). Any how to get through this?

**Comment by edschofield** [comment]
In that case ``future`` isn't installed properly on your system. Can you list any steps to reproduce this?

**Comment by ImmanuelSamuel** [comment]
I just installed anaconda3. 
```pip install future```
shows
Requirement already satisfied (use --upgrade to upgrade): future in /home/immanuel/programs/anaconda3/lib/python3.4/site-packages/future-0.15.2-py3.4.egg

**Comment by ImmanuelSamuel** [comment]
clean install cleared it
