### ISSUE TITLE
Method clobbered and wrong use of old_div in oldstr fixer

### ISSUE THREAD

**Issue by obestwalter** [PythonCharmers/python-future#190]
Disclaimer: I am a complete newbie to this package.

affected file: [fix_oldstr_wrap.py](https://github.com/PythonCharmers/python-future/blob/master/src/libfuturize/fixes/fix_oldstr_wrap.py)

I stumbled over this while trying to find out, why old_div fixes are still applied even if I deactivate them on the commandline (but this might be due to a newbie error). I had a look at uses of old_div in the codebase and stumbled over this:

    class FixOldstrWrap(fixer_base.BaseFix):
        [...]
        def transform(self, node, results):
            # some code here that works with oldstr
            [...]

        def transform(self, node, results):
            # this method clobbers the method above and does something with old_div
            [...]

Then there is also a second class in that file that also deals with old_div and not oldstr:

    class FixDivisionSafe(fixer_base.BaseFix):
        [....]

I don't know if this is the source of my particular problem but this is definitely a bug and a source of confusion. I guess this is never executed, because the first transform should be a match() method and this looks like some classic case of copy & paste gone wrong, but  I don't have a clue about the code base, so I just leave this smug report with you :)

**Comment by obestwalter** [comment]
see https://github.com/PythonCharmers/python-future/pull/202

**Comment by edschofield** [comment]
Thanks, Oliver! You're right that the module for that fixer had some broken code. That fixer is currently unused, and I'd be surprised if it's somehow imported automatically by the lib2to3 machinery, but I've cleaned it up. Let me know if you can deactivate `old_div` fixes now!

**Comment by obestwalter** [comment]
> Let me know if you can deactivate old_div fixes now!

@edschofield I filed this during evaluation of the library and since then moved on to a different approach. So I am not using python-future at the moment. Therefore I will not be able to verify the fix, especially as I was not quite sure anyway if I might be doing something else wrong.

**Comment by edschofield** [comment]
@obestwalter : okay thanks for letting me know!

Marking this as fixed.
