### ISSUE TITLE
How to convert `newbytes` to `native_bytes`?

### ISSUE THREAD

**Issue by ankostis** [PythonCharmers/python-future#200]
It seems that converting `newbytes` to `native_bytes` produces strange results:
For instance, here it is the _empty_ bytes.

```
>>> from future.builtins import bytes
>>> from future.utils import native_bytes

>>> nb = native_bytes(bytes(b''))
>>> print(repr(nb))
"b''"
>>> len(nb)
3
```

**Comment by ankostis** [comment]
Replying to my self (but need confirmation because I could not find it in the documentation). 
``bytes``'s method ``__native__())`` does the job, correct?

**Comment by edschofield** [comment]
Thanks for your question, Kostis. Yes, the ``__native__()`` method does the job. The recommended way to invoke this is by calling the ``future.utils.native()`` function.

**Comment by jmadler** [comment]
Closing for age.  Please re-open if this is important/valid.
