### ISSUE TITLE
isinstance('a', str) fails when import str

### ISSUE THREAD

**Issue by duckrojo** [PythonCharmers/python-future#229]
How should I deal with this?  All the code needs to have str() added? That would be cumbersome and won't work when used in function default keyword values. Thanks!

**Comment by cosama** [comment]
I can't believe this is just sitting here unanswered.

Try the following imports (mentioned here http://python-future.org/what_else.html#str):

```
from __future__ import unicode_literals
from builtins import str
```
The magic is the first line, which is not mentioned in http://python-future.org/compatible_idioms.html
Now `isinstance('a', str)` is `True`.

I think this can be closed now.
