### ISSUE TITLE
from past.builtins import apply

### ISSUE THREAD

**Issue by 631068264** [PythonCharmers/python-future#230]
what is `from past.builtins import apply` from [apply](http://python-future.org/compatible_idioms.html#apply) 

```
Traceback (most recent call last):
  File "/Users/wyx/workspace/aio_web/db/smartsql.py", line 4, in <module>
    from past.builtins import apply
ImportError: No module named 'past'
```

**Comment by edschofield** [comment]
@631068264: See the top of that document. The `past` package is distributed with `future` on PyPI, so run `pip install future`.
