### ISSUE TITLE
Does this lib support something like `a, *b = [1, 2, 3]`?

### ISSUE THREAD

**Issue by kxxoling** [PythonCharmers/python-future#239]
I didn't find it in the document, but really appreciate this feature in Python 3.

**Comment by edschofield** [comment]
No, it doesn't; Python-Future can't currently change syntax, and it couldn't do this without resorting to dark magic...

There could potentially be a utility function in `future.utils` that helps to turn this:

```
a, *b = [1, 2, 3]
```

into something like this on Py2&3:

```
a, b = unpack([1, 2, 3], starred=1)
```

Would this actually help? I expect not much. And the more complex examples in the Python 3.5 What's New notes don't seem to lend themselves as well to a helper function like this. Unless you have some ideas?

**Comment by kxxoling** [comment]
@edschofield I guess it could be implemented by doing something with the AST or doing some hacks with customized encoding type. Unfortunately I've never implemented these thing. But I think it would be great if it's supported.

**Comment by jayvdb** [comment]
To support this, another parser, capable of understanding Python 3.x compatible syntax, would need to be written for Python 2.7. It could then convert the code to the Python 2.7 ast, and let the runtime load it.
Not easy, and IMO not in scope of python-future.
