### ISSUE TITLE
distribute python wheels

### ISSUE THREAD

**Issue by graingert** [PythonCharmers/python-future#250]
By releasing as a Python wheel as well as a source distribution, you can speed up end user’s installs.

**Comment by jmadler** [comment]
Looks like this was added with PR #271.  

If I'm mistaken, please re-open.  I'm doing some housekeeping and may have not looked closely enough :)

**Comment by graingert** [comment]
Do you have a wheel release on PyPI?

**Comment by tucked** [comment]
> Do you have a wheel release on PyPI?

Negative: https://pypi.org/project/future/#files
Note that #271 would cause a universal wheel to be made _if wheels were being made_ 😋 

Also, note that this prevents `pip download` from working with `--platform` on downstream deps:
```
$ pip download --platform linux_x86_64 --only-binary=:all: cookiecutter
Collecting cookiecutter
  Downloading https://files.pythonhosted.org/packages/16/99/1ca3a75978270288354f419e9166666801cf7e7d8df984de44a7d5d8b8d0/cookiecutter-1
.6.0-py2.py3-none-any.whl (50kB)
    100% |████████████████████████████████| 51kB 178kB/s
  Saved ./cookiecutter-1.6.0-py2.py3-none-any.whl
Collecting jinja2>=2.7 (from cookiecutter)
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1
-py2.py3-none-any.whl
  Saved ./Jinja2-2.10.1-py2.py3-none-any.whl
Collecting click>=5.0 (from cookiecutter)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2
.py3-none-any.whl
  Saved ./Click-7.0-py2.py3-none-any.whl
Collecting future>=0.15.2 (from cookiecutter)
  Could not find a version that satisfies the requirement future>=0.15.2 (from cookiecutter) (from versions: )
No matching distribution found for future>=0.15.2 (from cookiecutter)
```

`pip wheel` can work around, but it doesn't have a `--platform` option (so you can't download for another machine).

**Comment by tucked** [comment]
(I don't have permission to reopen.)

**Comment by graingert** [comment]
@jmadler I cannot reopen either
