### ISSUE TITLE
surrogateescape handler broken when encountering UnicodeEncodeError

### ISSUE THREAD

**Issue by wence-** [PythonCharmers/python-future#256]
Consider:

```
$ python --version
2.7.9
```

```python
from future.utils.surrogateescape import register_surrogateescape
register_surrogateescape()
print u'\u03b1'.encode("iso-8859-1", "surrogateescape")
=> future/utils/surrogateescape.pyc in replace_surrogate_encode(mystring)
     84         if not 0xD800 <= code <= 0xDCFF:
     85             # Not a surrogate. Fail with the original exception.
---> 86             raise exc
     87         # mybytes = [0xe0 | (code >> 12),
     88         #            0x80 | ((code >> 6) & 0x3f),

NameError: global name 'exc' is not defined
```

This is because `replace_surrogate_encode` tries to refer to the exception of its calling context, which obviously fails.  A simple fix might be to pass that exception in as an argument.

**Comment by pombredanne** [comment]
@edschofield do you want a patch for this? This is an easy fix I guess?

**Comment by edschofield** [comment]
@pombredanne: Yes please! That would be very helpful.

**Comment by pombredanne** [comment]
@anbai106 you can feed unicode paths alright all the way on Windows and macOS on Python 2.
On Linux, this is where surrogate escaping comes into play hence the fact you hit the bug there quite likely

**Comment by graingert** [comment]
@jmadler @wence- looks like this was fixed here: 
https://github.com/PythonCharmers/python-future/commit/da5e6d241bb6a58a5a1e2e941602037d47115781
