### ISSUE TITLE
variable ``future.utils.PY3`` -- is time bomb

### ISSUE THREAD

**Issue by antonov-impulsm** [PythonCharmers/python-future#276]
issue same as in ``six``-project: https://bitbucket.org/gutworth/six/issues/22/variable-sixpy3-is-time-bomb ..

(same as in ``six``-project you may mark this issue as ``wontfix`` . but , ok i warned about this issue )

**Comment by polymorphm** [comment]
see this file as a good pattern -- https://github.com/python/cpython/blob/master/Lib/asyncio/compat.py

**Comment by benjaoming** [comment]
Following that logic, `six.PY2` should be `PY2 = sys.version_info[0] >= 2` ?? :)

Pretty sure this can just be closed.

**Comment by polymorphm** [comment]
> Following that logic, six.PY2 should be PY2 = sys.version_info[0] >= 2 ??

yes. exactly.

but variable just ``PY2`` for six/python-future is *not needed* -- if variable ``PY3`` exists.

> Pretty sure this can just be closed.

of course you can. when time-bomb will explode -- I just will reopen this issue-ticket :-)

**Comment by jmadler** [comment]
I've adjusted some of the conditionals, but this is not sufficient for Py4.0 support.  We'll cross that bridge once it's laid down...
