### ISSUE TITLE
cmp solution does not work --> SyntaxError

### ISSUE THREAD

**Issue by cclauss** [PythonCharmers/python-future#297]
http://python-future.org/compatible_idioms.html?highlight=cmp#cmp recommends
`cmp = lambda(x, y): (x > y) - (x < y)` but that is a SyntaxError in Python 3.6...

`python3 -c 'cmp = lambda(x, y): (x > y) - (x < y)'`  # --> SyntaxError

What is the correct approach?

**Comment by QuLogic** [comment]
Remove the first parentheses: `python3 -c 'cmp = lambda x, y: (x > y) - (x < y)'`

**Comment by cclauss** [comment]
Can we get the webpage changed to match?

**Comment by jmadler** [comment]
I've merged it in and will update the website on the next release cut.
