### ISSUE TITLE
HTTPS to python-future.org (https://python-future.org) down

### ISSUE THREAD

**Issue by cooperlees** [PythonCharmers/python-future#324]
Your website's HTTPS is down. Didn't know how else to notify.

Can ping 192.81.210.173 ahd http. Just not https.

Your pypi links (thus setup.py) point @ https.

**Comment by cooperlees** [comment]
https://github.com/PythonCharmers/python-future/pull/325 is up.

**Comment by jaraco** [comment]
Better would be to serve on HTTPS.

**Comment by cooperlees** [comment]
Totally, but it would be nice to have working links too in the meantime.

There is obviously no urgency here ...

**Comment by jmadler** [comment]
Dupe of #358
