### ISSUE TITLE
print function Runtime error for Flush option

### ISSUE THREAD

**Issue by workingmonk** [PythonCharmers/python-future#329]
Found the issue while fixing https://github.com/googlesamples/assistant-sdk-python/pull/182

Using the code `print('Registering....', end='', flush=True)` in python 2.7 causes the following error

Without the import statement, it is a Compilation error
https://ideone.com/FtNFzO

With the import statement, it is a RunTime error for flush being an invalid argument
https://ideone.com/a00yNv

**Comment by TheTechRobo** [comment]
Saw this on StackOverflow and am using it in my project for Python 2 compatibility. It seems to work.
```
if sys.version_info[:2] < (3, 3): #https://stackoverflow.com/a/35467658/9654083
    old_print = print
    def print(*args, **kwargs):
        flush = kwargs.pop('flush', False)
        old_print(*args, **kwargs)
        if flush:
            file = kwargs.get('file', sys.stdout)
            # Why might file=None? IDK, but it works for print(i, file=None)
            file.flush() if file is not None else sys.stdout.flush()
```
