### ISSUE TITLE
Support new `default` argument for builtin `max` and `min`

### ISSUE THREAD

**Issue by lerks** [PythonCharmers/python-future#334]
Starting in Python 3.4 the builtins `max` and `min` support a new keyword-only argument `default` that allows to specify the value to be returned in case of an empty sequence. It appears that `future` doesn't provide replacement builtins with that semantics. Shouldn't it do so?

**Comment by SameeraSomisetty** [comment]
Looking into this issue.

**Comment by megies** [comment]
Just for reference, see #459
