### ISSUE TITLE
Is there an active fork of this repo?

### ISSUE THREAD

**Issue by cclauss** [PythonCharmers/python-future#347]
I use this code frequently and I find that the absolute_imports changes can create new syntax errors.

I believe there are several other nice improvements that could be made.  I guess that I am not alone because there are currently 30 open PRs and 136 open issues yet there has not been a new merge in 14 months?

**Comment by jmadler** [comment]
This project is now being actively maintained.  I reached out to Ed over email, we met over VC and I offered to assist maintaining this project going forward.
