### ISSUE TITLE
standard_library.install_aliases() imports my project test module

### ISSUE THREAD

**Issue by PJCampi** [PythonCharmers/python-future#352]
Hi there,

The install_aliases() module attempts to import the `test ` module:
```
    try:
        import test
    except ImportError:
        pass
    try:
        from future.moves.test import support
    except ImportError:
        pass
    else:
        test.support = support
        sys.modules['test.support'] = support
```
It is meant to import the Python  `test ` module, but in practice it imports the first module named  `test ` in PYTHONPATH.

Many programmers recommend a python project structure including a `test ` folder. The install_alias incorrect import statement must be quite common.

Br,

Pierre-Jean

**Comment by QuLogic** [comment]
You shouldn't name things to match the standard library (whether `test` is super generic and shouldn't be in the standard library is a different discussion); the common recommendation is `tests`, not `test`.

**Comment by PJCampi** [comment]
That's what I ended up doing :)
