### ISSUE TITLE
Syntax error after stage1 due to 'lib2to3.fixes.fix_execfile'

### ISSUE THREAD

**Issue by wluebbe** [PythonCharmers/python-future#37]
After applying `futurize --stage1 -w sage` the following syntax error occured:

`File "/home/wluebbe/sage-6.2.beta3-future/local/lib/python2.7/site-packages/sage/misc/preparser.py", line 1760
    exec(compile(open(fpath).read(), fpath, 'exec'), globals)
SyntaxError: function 'load' uses import * and bare exec, which are illegal because it contains a nested function with free variables`

The offending line was changed by `fix_execfile`:

@@ -1755,7 +1757,7 @@
`if fpath.endswith('.py'):
         exec_file_is(fpath)`
`-        execfile(fpath, globals)`
`+        exec(compile(open(fpath).read(), fpath, 'exec'), globals)
     elif fpath.endswith('.sage'):`

To be "uncontroversial" `fix_execfile` may be moved to stage2 (as `fix_exec` already is).

**Comment by jmadler** [comment]
Closing as this conversation has stalled and there appears to be no remaining action for `python-future`.  Please reopen if I may be mistaken :)
