### ISSUE TITLE
Is there a way to access version information in the module?

### ISSUE THREAD

**Issue by reedog117** [PythonCharmers/python-future#378]
Looking for a way to access version information in the future module.

My goal is to add a check to some code I'm writing to ensure a recent version of future is installed on the system. I've noticed bugs running old versions of future with some of my code, so I'd like to add a version check step at runtime.

**Comment by jmadler** [comment]
Yes, it's accessible: 

```
>>> import future
>>> dir(future)
['__author__', '__builtins__', '__copyright__', '__doc__', '__file__', '__license__', '__name__', '__package__', '__path__', '__title__', '__ver_major__', '__ver_minor__', '__ver_patch__', '__ver_sub__', '__version__']
>>> future.__ver_major__
0
>>> future.__ver_minor__
17
>>> future.__ver_patch__
0
>>> future.__version__
'0.17.0'
>>>
```
