### ISSUE TITLE
No "What's New" section for 0.17.0

### ISSUE THREAD

**Issue by adamchainz** [PythonCharmers/python-future#402]
Just upgrading from 0.16.0, I can't find any release notes. [What's New](http://python-future.org/whatsnew.html) was last updated for 0.16.0, I guess it was missed in this release?

**Comment by adamchainz** [comment]
Oh no I see they were updated in 99948c387702496274147a71f8bf0e600569f6b5 , I guess the docs build is failing

**Comment by cclauss** [comment]
Same for 0.17.1

**Comment by bladeoflight16** [comment]
Same for 0.18

**Comment by sfdye** [comment]
Merge with #511
