### ISSUE TITLE
raw_input breaking with multiple futurize passes

### ISSUE THREAD

**Issue by jb2780** [PythonCharmers/python-future#427]
Let's start with a python file (test.py) containing a single line:

`test = raw_input("Test: ")`

Pass 1: Running **futurize.exe test.py --both-stages -w** converts this to:

```
from builtins import input
test = input("Input: ")
```

Pass 2: Running **futurize.exe test.py --both-stages -w** again converts this to:

```
from builtins import input
test = eval(input("Input: "))
```

The second pass is incorrect. The presence of "from builtins import input" should indicate that the bare input has already been corrected.

Note that **--both-stages** can be replaced with **--fix lib2to3.fixes.fix_input --fix lib2to3.fixes.fix_raw_input  --fix libfuturize.fixes.fix_future_builtins**.

**Comment by guyer** [comment]
👍
