### ISSUE TITLE
Return NotImplemented in newstr.__eq__

### ISSUE THREAD

**Issue by max-vogler** [PythonCharmers/python-future#432]
We stumbled upon an edge case in our codebase, related to `newstr.__eq__` returning `False` instead of `NotImplemented`. Is this intended?

https://github.com/PythonCharmers/python-future/blob/29605d694a75de09a80bda42d33a0ddcb391e51e/src/future/types/newstr.py#L288-L293

For clarification, returning `False` in `__eq__`  indicates a successful comparison of inequal objects. Judging by the code, the `else` branch should return `Notimplemented`, which indicates that the check was not successful. This allows the other object's `__eq__` to be called.

See [Python 2 data model](https://docs.python.org/2/reference/datamodel.html#object.__eq__) and [Python 3 data model](https://docs.python.org/3/reference/datamodel.html#object.__eq__):
> A rich comparison method may return the singleton NotImplemented if it does not implement the operation for a given pair of arguments. By convention, False and True are returned for a successful comparison. 
> [...]
> Numeric methods and rich comparison methods should return [NotImplemented] if they do not implement the operation for the operands provided. (The interpreter will then try the reflected operation, or some other fallback, depending on the operator.)

Our codebase has string-like objects that are not a subclass of `str` or `unicode` but have identical semantics. Whether this is a good idea is big internal debate, but for now it is part of the codebase. This leads to asymmetrical equality, which we would like to fix:
```py
our_str = OurCustomString("foobar")
new_str = future.builtins.str("foobar")

our_str == new_str  # -> True
new_str == our_str  # -> False
```

**Comment by jmadler** [comment]
Using this code as a reference: 
```test.py
class CustomStringClass(object):

    def __init__(self, string):
        self.string = string

    def __str__(self):
        return self.string

fb = "foobar"
cs = CustomStringClass("foobar")
print(type(fb), type(cs))
print(fb == cs)
print(cs == fb)
```

Python 3 and 2's built-in string functions produce the same result: 
```
<class 'str'> <class '__main__.CustomStringClass'>
False
False
```

This behavior is true regardless of the presence of the __str__ method, suggesting the reference interpreters do not coerce the object into a string primitive type as part of its __eq__ implementation.

It's true that this is misaligned with the documented data model, and I'll follow-up with the core python development team.  I'd prefer to keep the behavior consistent with python built-ins as much as possible, so we'll follow whatever decision is made there.

**Comment by max-vogler** [comment]
The issue we encountered is slightly different. `CustomStringClass` does not define `__eq__` and coercion is not what I would expect.

Instead, consider this example:
```python
from __future__ import print_function
import platform
from future.types import newstr


class CustomString(object):

    def __init__(self, string):
        self.string = string

    def __eq__(self, other):
        if isinstance(other, (str, newstr)):
            return self.string == other
        else:
            return NotImplemented


native = "foo"
custom = CustomString("foo")

print("Python", platform.python_version())
print("native", native == custom, custom == native)

if platform.python_version_tuple()[0] == "2":
    future = newstr("foo")
    print("future", future == custom, custom == future)

```

Running it with Python 2 and 3 results in the following output:
```
> python2 misc/futuretest.py
Python 2.7.15
native True True
future False True

> python3 misc/futuretest.py
Python 3.7.2
native True True
```

Both Python 2 and 3's native string types correctly handle the symmetry of `==`. `future.types.newstr` on the other hand does not expose this symmetry, because its `__eq__` implementation returns `False` instead of `NotImplemented`.

**Comment by ethanfurman** [comment]
Max-Vogler is correct -- when implementing the rich-comparison operators care should be taken to only return True/False when the object knows how it compares to the other object.  If it doesn't know, it should `return NotImplemented`<sup>1</sup> and let Python figure out the next step.

---

<sup>1</sup> Note:  `raise NotImplementedError` is not the same and should not be used.

**Comment by jmadler** [comment]
Ah!  I was unaware of that detail about the layer of indirection between __eq__() and the == operator.  Sorry about that.  I'll get this addressed.
