### ISSUE TITLE
changelog incorrect (typo?)

### ISSUE THREAD

**Issue by pjw91** [PythonCharmers/python-future#438]
In first item of [What's New 0.16.0](https://github.com/PythonCharmers/python-future/blob/master/docs/whatsnew.rst#whats-new-in-version-0160-2016-10-27):
> Fix newbytes constructor bug. (Issue #163)
However, issue 163 seemed unrelated to newbytes.

It seems that #173 / #171 is about newbytes.

Note that the website (python-future.org) is outdated.

**Comment by jmadler** [comment]
Yeah, looks like you may be right.  I've submitted a PR for @edschofield to review as he may have more context.
