### ISSUE TITLE
Add pre-commit support

### ISSUE THREAD

**Issue by alekhrycaiko** [PythonCharmers/python-future#443]
I'm interested in consuming python-future through git-commit hooks, and would like the ability to integrate this tool in a [pre-commit](https://github.com/pre-commit/pre-commit) tool chain. I'd be willing to add this update if there's any appetite for having this added to the repository.

**Comment by jmadler** [comment]
Please do :)

**Comment by sfdye** [comment]
Would #543 close this?

**Comment by alekhrycaiko** [comment]
Yes it should. Thanks!

**Comment by sfdye** [comment]
This is done, just pending release
