### ISSUE TITLE
broken exception argument re-raising

### ISSUE THREAD

**Issue by spaceone** [PythonCharmers/python-future#455]
```
import traceback


def foo():
        raise ValueError('test from foo')


def bar():
        try:
                foo()
        except ValueError, exc:
                raise ValueError, exc


try:
        foo()
except ValueError as exc:
        print(traceback.format_exc())
        print(repr(exc.args))
try:
        bar()
except ValueError as exc:
        print(traceback.format_exc())
        print(repr(exc.args))
```

futurize transforms this into:
```
@@ -8,8 +9,8 @@
 def bar():
        try:
                foo()
-       except ValueError, exc:
-               raise ValueError, exc
+       except ValueError as exc:
+               raise ValueError(exc)

```

Actual behavior:
The second print prints:
`(ValueError('test from foo',),)`

Expected behavior:
The second print prints:
`ValueError: test from foo`

**Comment by vermaport** [comment]
Working on this at the PyCon sprint. The [`FixRaise`](https://github.com/PythonCharmers/python-future/blob/master/src/libfuturize/fixes/fix_raise.py) fixer doesn't attempt to detect if `exc` is an instance of `ValueError`, [as it probably should](https://docs.python.org/2/reference/simple_stmts.html#the-raise-statement). This can only be detected at runtime. I propose that we call `future.utils.raise_()` in cases where the second argument to `raise` is not an obvious literal (`5`, `None`, `"foo"`, etc.), i.e.

```
raise ValueError, exc
```
would be rewritten to
```
from future.utils import raise_
raise_(ValueError, exc)
```

I'll add code to `raise_()` to handle this case which, incidentally, should fix #387, too.
