### ISSUE TITLE
0.18 release?

### ISSUE THREAD

**Issue by colinhowe** [PythonCharmers/python-future#478]
Hi,

Any idea when 0.18 might be coming? We've stumbled onto the division bug (#434) and want to be able to run a released version rather than master :)

Is there anything that we can help with in getting this out?

Cheers,
Colin

**Comment by jmadler** [comment]
Hey Colin!  At the moment, I'm the only one working on this project, and only in my spare time.  I'll cut a release today to get master out onto PyPI, but there's quite a roadmap to final release, and I need some help.  

The roadmap is on GitHub, with appropriate issues tagged with a version number (0.18-1.0).  Contributing to these issues would be super helpful.

Jordan

**Comment by justinfx** [comment]
Hoping to see this release soon. I just had to fix a production bug from the `old_div` division bug and ended up finding that it is fixed in 0.18. Thanks!
