### ISSUE TITLE
past/types/oldstr.py:33: DeprecationWarning: invalid escape sequence \d

### ISSUE THREAD

**Issue by ssbarnea** [PythonCharmers/python-future#479]
That warnings appears with python3.6:
```
past/types/oldstr.py:33: DeprecationWarning: invalid escape sequence \d
```
Apparently the broken code is inside docstring example but is enough to pollute any test executions on a library using python-future.

An easy solution is to replace the example with another escape which is still valid, like a ``\n`` instead of ``\\d``. Also a release would be needed.

**Comment by Harmon758** [comment]
Note, this now produces a SyntaxWarning with Python 3.8:
```
C:\Program Files\Python38\lib\site-packages\past\types\oldstr.py:20: SyntaxWarning: invalid escape sequence \d
  """
```
> A backslash-character pair that is not a valid escape sequence generates a [DeprecationWarning](https://docs.python.org/3.8/library/exceptions.html#DeprecationWarning) since Python 3.6. In Python 3.8 it generates a [SyntaxWarning](https://docs.python.org/3.8/library/exceptions.html#SyntaxWarning) instead.

https://docs.python.org/3.8/whatsnew/3.8.html

> Changed in version 3.6: Unrecognized escape sequences produce a [DeprecationWarning](https://docs.python.org/3.8/library/exceptions.html#DeprecationWarning).
> 
> Changed in version 3.8: Unrecognized escape sequences produce a [SyntaxWarning](https://docs.python.org/3.8/library/exceptions.html#SyntaxWarning). In some future version of Python they will be a [SyntaxError](https://docs.python.org/3.8/library/exceptions.html#SyntaxError).

https://docs.python.org/3.8/reference/lexical_analysis.html

https://bugs.python.org/issue32912, https://github.com/python/cpython/pull/9652, https://github.com/python/cpython/commit/6543912c90ffa579dc4c01e811f9609cf92197d3

**Comment by jmadler** [comment]
Can you submit a bugfix please? I'll include it in a release in the next few days.

**Comment by Harmon758** [comment]
There already is one, #480, which referenced as closing this issue.

**Comment by ssbarnea** [comment]
Is this project effectively dead? PR is present and is a one char fix. What prevents merging and making a release?
