### ISSUE TITLE
Is the latest version 0.17.0 or 0.17.1?

### ISSUE THREAD

**Issue by wangkirin** [PythonCharmers/python-future#500]
Hi community:
       We found that in `pypi` the latest version of future is `0.17.1`,   see https://pypi.org/project/future/,  but in this repository the latest version is `0.17.0`,  could anyone tell me which is the offcial one?

**Comment by jdanekrh** [comment]
Looking into releasenotes, 0.17.1 was to fix a packaging error. It does not have a corresponding tag in the repo. https://github.com/PythonCharmers/python-future/blob/master/docs/whatsnew.rst

It would be good to create the tag and GitHub release as well. For both 0.17.1 and 0.18.0. Just to be neat and clean.

**Comment by jmadler** [comment]
There's a few outstanding high-priority bugs with 0.18.0 that I'd like to get patches in for to release a 0.18.2.  Once that's done, I'll update the release notes and chase up Ed for access to update the site.  

Thanks for the reminder folks -- this project is woefully understaffed...

**Comment by edschofield** [comment]
Hi @jmadler: thanks for your recent work merging PRs etc. and preparing the next release. I'm standing by to update the site to 0.18.2 ...

**Comment by sfdye** [comment]
Close in favor of #511

**Comment by sfdye** [comment]
BTW we have retroactively populated all releases from 0.17.1 to 0.18.2.

**Comment by Uzume** [comment]
> BTW we have retroactively populated all releases from 0.17.1 to 0.18.2.

@sfdye Finally! Thank you, very much.
