### ISSUE TITLE
max() over itertools.ifilter() is broken in 0.18.0

### ISSUE THREAD

**Issue by xeron** [PythonCharmers/python-future#510]
Python 2.7.16.
macOS 10.14.6.

Reproducible with:

```python
import builtins
import operator

from itertools import ifilter
from random import shuffle


class Backend(object):
    def __init__(self, priority):
        super(Backend, self).__init__()
        self.priority = priority


def max(*args, **kwargs):
    """
    Add support for 'default' kwarg.

    >>> max([], default='res')
    'res'

    >>> max(default='res')
    Traceback (most recent call last):
    ...
    TypeError: ...

    >>> max('a', 'b', default='other')
    'b'
    """
    missing = object()
    default = kwargs.pop('default', missing)
    try:
        mmax = builtins.max(*args, **kwargs)
        return mmax
    except ValueError as exc:
        if 'empty sequence' in str(exc) and default is not missing:
            return default
        raise


by_priority = operator.attrgetter('priority')

backends = [Backend(5), Backend(1), Backend(0.5), Backend(0.6)]

while True:
    shuffle(backends)
    filtered_backends = ifilter(None, backends)
    max_object = max(filtered_backends, key=by_priority)
    print(max_object.priority)
    if max_object.priority != 5:
        exit(1)
```

Can't reproduce with `0.17.1`.

This affects older versions of `keyring` library using similar code to select keychain backend where it wants max priority backend but returns the wrong one.

Also it looks like it depends on the order of the list.

**Comment by jmadler** [comment]
Can you submit a bugfix please?  I'll include it in a release in the next few days.

**Comment by xeron** [comment]
Sorry, I have no idea how to fix this. We've just downgraded to `0.17.1` for now.

**Comment by gazpachoking** [comment]
I think I'm running into a related issue. The new min and new max function consume the first item of an iterator before passing to the underlying min and max functions. I'll take a stab at a PR if I get time tonight.

**Comment by megies** [comment]
I'm running into problems with with min/max of generators as well. Can't tell what the above code is doing, but it sounds related.

For me specifically, the problem seems to be `min()` or `max()` over a generator with only a single item in it. Here is a minimal example:

```python
from future.builtins import *
min(x for x in [1])
```

I bisected this and it starts failing on master with commit f141395ce73acc3d1461ff21a29813c1e9e15baf.

I checked current state of #514 and can confirm that it fixes this issue. Thanks @gazpachoking

**Comment by jmadler** [comment]
Thanks megies for the confirmation!

Thanks all for helping make this software better :)

**Comment by xeron** [comment]
Fix has not been merged yet, right?

**Comment by megies** [comment]
It's been merged now :)
