### ISSUE TITLE
Add OrderedDict and Enum classes

### ISSUE THREAD

**Issue by krischer** [PythonCharmers/python-future#52]
This would be really useful for many purposes. Many larger libraries have their own versions of theses types.

`collections.OrderedDict` was introduced in Python 2.7 and `enum.Enum` in Python 3.4.

I am not sure what the project's stance is on things like this but both could be easily backported so I thought I'd bring it up.

**Comment by graingert** [comment]
>The only statistics backport I could find: https://bitbucket.org/tiran/backports.statistics/overview
Not sure how stable that is though.

@krischer I've uploaded that package to PyPI at https://pypi.python.org/pypi/backports.statistics
