### ISSUE TITLE
Request to define a ``newbytes3`` type for Py3.3 and Py3.4 only with % formatting (backport of PEP 461 from Py3.5)

### ISSUE THREAD

**Issue by edschofield** [PythonCharmers/python-future#55]
This request is for a subclass of `bytes` on Py3.3 and Py3.4 that backports % formatting from Py3.5 (PEP 461).

See also issue #54. 

See http://bugs.python.org/issue20284 for sample implementations in C :-/

**Comment by jmadler** [comment]
I believe this is addressed by #359 
Please reopen if I may be mistaken :)
