### ISSUE TITLE
0.18.X release missing

### ISSUE THREAD

**Issue by foreignmeloman** [PythonCharmers/python-future#557]
Hi!

I was not able to find the latest release version or tag in the releases tab. Are the releases moved somewhere else?

**Comment by goldstar611** [comment]
+1,
I'd like to use 0.18.2 release in a flatpak and it would be great to have here especially since all of the older versions are listed

**Comment by sfdye** [comment]
Hi the new version (0.18.2) is already available on PyPI, you install it:
`pip install --upgrade future` or `pip install future==0.18.2`

We will retro populate the Github release soon.

**Comment by sfdye** [comment]
Retroactively populated releases from 0.17.1 - 0.18.2:

https://github.com/pythoncharmers/python-future/releases
