### ISSUE TITLE
xmlrpclib is not included into fix_future_standard_library fixer

### ISSUE THREAD

**Issue by PovelikinRostislav** [PythonCharmers/python-future#567]
From the documentation:
```
lib2to3.fixes.fix_imports   # Called by libfuturize.fixes.fix_future_standard_library
```

But it's not working for `xmlrpclib` library. Explicit enabling of `-f lib2to3.fixes.fix_imports` adds renaming of `xmlrpclib` to `xmlrpc.client` and other needed stuff.

**Comment by PovelikinRostislav** [comment]
Not applicable, I missed the first and second stages in doc, sorry :)

**Comment by Amir-Hadadi** [comment]
Where did you see this is not applicable? what's the solution?
