### ISSUE TITLE
Drop support for Python 2.6 and Python 3.3

### ISSUE THREAD

**Issue by sfdye** [PythonCharmers/python-future#580]
Similar to https://github.com/davidhalter/jedi/issues/1016

Dropping support for EOL versions of Python. 

Google BigQuery result for all history downloads by python version:
```
$ pypinfo --percent future pyversion

| python_version | percent | download_count |
| -------------- | ------- | -------------- |
| 3.7            |  42.61% |      8,388,003 |
| 3.6            |  21.85% |      4,302,198 |
| 2.7            |  14.68% |      2,889,720 |
| 3.8            |  12.53% |      2,467,021 |
| 3.5            |   7.18% |      1,414,377 |
| 3.9            |   1.00% |        197,807 |
| 3.4            |   0.13% |         26,235 |
| 2.6            |   0.00% |            893 |
| 3.10           |   0.00% |            433 |
| 3.3            |   0.00% |             15 |
| Total          |         |     19,686,702 |
```

You can see that 2.6 and 3.3 are both ~0.0%, so it should be safe to drop. Worst case if anyone wants to use `future` for Python 2.6 and Python 3.3, they can always use an older version of `future`.

Python 2.6 is blocking us from moving to Github Action, since Github's https://github.com/actions/setup-python does not support Python 2.6 anymore (see [full list](https://github.com/actions/python-versions/blob/main/versions-manifest.json)).

**Comment by jmadler** [comment]
We are a version compatibility layer, we should aim as much as is reasonable to cover the versions we can.  This is not a compelling enough reason to drop py26/py33 in my opinion.  It is better to change our CI system than it is to drop py26 and py33.

**Comment by sfdye** [comment]
> We are a version compatibility layer, we should aim as much as is reasonable to cover the versions we can.

That is true. As you can see, all history downloads of 2.6 and 3.3 are pretty tiny compared to other versions. I was trying to see if there is any downloads of python 2.6 and 3.3 after 2019 by
`pypinfo --start-date 2019-01-01 future pyversion`, but BigQuery is giving me `Quota exceeded` error. 

Anyway the downstream can still use `future` with EOL'd python by pinning to an old version, e.g. `future==0.18.2`, so strictly speaking there is a work-around. As the Python community has moved on to Python 3 (dropping Python 2.7), I feel as an upstream library we should also move on by at least dropping Python 2.6 support on the main branch.

**Comment by jmadler** [comment]
No.  We are not a typical upstream library.  We should not drop support for python versions unless there's a compelling reason to do so.  I see no such reason.
