### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by thiline** [PythonCharmers/python-future#587]
Hi,

I get this error;
ImportError: cannot import name 'connect_to_workers' from 'future'

when using the below code segment in my program.
from future import connect_to_workers, connect_to_crypto_provider

Could you please explain any possible reason for that and a remedy for that ?

Thank you !

**Comment by edschofield** [comment]
Hi @thiline , Your code snippet and those errors are nothing to do with the `future` package.
