### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by megies** [PythonCharmers/python-future#61]
Are there plans for Debian `.deb` packages? @obspy is distributed as Debian packages and the next major release will have a dependency on `python-future`.. which is still unresolved for Debian packaging..

**Comment by megies** [comment]
Just an FYI, `python-future` is in Debian jessie backports: https://packages.debian.org/jessie-backports/python-future

**Comment by jmadler** [comment]
Closing for age.  Please re-open if this is important/valid.
