### ISSUE TITLE
Missing PyPI package classifier

### ISSUE THREAD

**Issue by douglas-raillard-arm** [PythonCharmers/python-future#624]
setup.py is missing some classifiers to indicate supported Python versions, as it only lists up to Python 3.7:
https://github.com/PythonCharmers/python-future/blob/3dc7acc8e5a4266df6c823b9350a731dd7df6124/setup.py#L95

If the intent is to support all Python 3 versions (which seems to be the case), it might make sense to only keep `Python :: 3` and remove all the `Python :: 3.X` ones.

**Comment by edschofield** [comment]
Thanks for reporting this, @douglas-raillard-arm . Fixed in `master`.
