### ISSUE TITLE
Python 3.12 removes imp module

### ISSUE THREAD

**Issue by odie5533** [PythonCharmers/python-future#625]
Future relies on the imp module in [standard_library](https://github.com/PythonCharmers/python-future/blob/master/src/future/standard_library/__init__.py#L65), used for things like `from future.standard_library import hooks`. In Python 3.12, the module has been [completely removed](https://docs.python.org/3.12/whatsnew/3.12.html#imp). Future needs to switch to use importlib.

```python
# future/standard_library/__init__.py
        name = bits[0]
        module_info = imp.find_module(name, path)
        return imp.load_module(name, *module_info)
```

```
    from future.standard_library import hooks
  File "/home/odie5533/test/venv/lib/python3.12/site-packages/future/standard_library/__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

# Workaround

If your code is like this
```python
# Python 2 and 3: alternative 2
from future.standard_library import hooks

with hooks():
    from urllib.parse import urlparse, urlencode
    from urllib.request import urlopen, Request
    from urllib.error import HTTPError
```
You can rewrite it using the try-except form in the [Cheat Sheet](https://python-future.org/compatible_idioms.html?highlight=urllib#urllib-module).

```python
# Python 2 and 3: alternative 4
try:
    from urllib.parse import urlparse, urlencode
    from urllib.request import urlopen, Request
    from urllib.error import HTTPError
except ImportError:
    from urlparse import urlparse
    from urllib import urlencode
    from urllib2 import urlopen, Request, HTTPError
```

**Comment by odie5533** [comment]
Tried my hand at a PR but I can't dip into another codebase right now and I'm unsure of the state of some of the tests.

**Comment by amotl** [comment]
Thank you for submitting GH-626. We are also running into this over at mqttwarn.

- https://github.com/mqtt-tools/mqttwarn/pull/685

**Comment by liquidsec** [comment]
Any chance for a real fix and not just a workaround? I've got a project that uses this as a dependency 2 levels down, causing me to be python 3.12 incompatible.

**Comment by nsoranzo** [comment]
@liquidsec Have a look at https://github.com/PythonCharmers/python-future/pull/632 .
