### ISSUE TITLE
Future imports above encoding?

### ISSUE THREAD

**Issue by guettli** [PythonCharmers/python-future#97]
Is this you inted? The imports are above the "# -_\- coding: utf-8 -_-" line.

AFAIK the coding should be at the top of the file.

```
+from __future__ import print_function
+from __future__ import division
+from __future__ import absolute_import
+from __future__ import unicode_literals
# -*- coding: utf-8 -*-
```

I think it is a bug.

What happens if there is "#!/usr/bin/python" at the top?

**Comment by bertsky** [comment]
I believe this needs to be re-opened. It only works if the encoding specifier is in the very first line (not if it's in the second), and only if it uses the `-*-` convention. But PEP 263 specifies the following regex (for the first or second line):

```regex
^[ \t\f]*#.*?coding[:=][ \t]*([-_.a-zA-Z0-9]+)
```

This licenses usage like the following (as can be seen in pyleptonica):

```python

# coding: utf-8
```

But this gives (with `future==0.18.2`): 

```python
from __future__ import absolute_import

# coding: utf-8
```

...which does not work anymore, and yields a follow-up error in Python 2 (`SyntaxError: Non-ASCII character` ...)
